name: personal_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  pie_chart: ^5.3.2
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  date_format: ^2.0.7
  currency_text_input_formatter: ^2.1.10
  money_formatter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
          style: italic
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
          weight: 700
